### ISSUE TITLE
3 🥕 Support inserting multiple rows with a single call

### ISSUE THREAD

**Issue by darioteixeira** [issuu/ppx_mysql#33]

**Comment by Leonidas-from-XIV** [comment]
I am a bit surprised why a new keyword is required, since the fact that a keyword is needed, since the queries themselves already signify that a list is required. `VALUES` is an indicator that a list is required (with a special case of a single value), whereas `SELECT user_name FROM users WHERE user_id = ?` indicates that `user_id` is a scalar since if `user_id` were a list it'd require `WHERE user_id IN ?`.

Personally I prefer to keep the type ascriptions in the SQL code, like HugSQL https://www.hugsql.org/#param-value-list where the fact that a list is required is indicated by `:v:` (though of course in our case it would make more sense to use the sigils that we use).

**Comment by darioteixeira** [comment]
At the moment ppx_mysql does not try to parse SQL, and that's a can of worms that I'd rather not open. Moreover, consider a query like `UPDATE users SET name = ? WHERE id = ?`. Is that singular or plural? The user may want to invoke it repeatedly for each element in the list `[("john", 1); ("mary", 2)]`. but there's no way to know just by looking at the SQL code!

**Comment by Leonidas-from-XIV** [comment]
How can `UPDATE users SET name = ? WHERE id = ?` ever apply to the list of values you mentioned?

But I see your point of not wanting to parse SQL. This is why I think a notation like `:v:` would make sense.

**Comment by darioteixeira** [comment]
Suppose the user wants to execute `UPDATE users SET name = ? WHERE id = ?` both for `("john", 1)` and `("mary", 2)` without going through the whole connect-prepare-execute dance twice.
